openapi: 3.0.0
info:
  version: 1.0.0
  title: Product API
servers:
  - url: https://3coawsqalb.execute-api.eu-west-1.amazonaws.com/
paths:
  /products:
    get:
      summary: Get Product List
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              example:
                - id: 1
                  name: Product 1
                  description: Description for Product 1
                - id: 2
                  name: Product 2
                  description: Description for Product 2
        "500":
          description: Internal Server Error
          content:
            application/json:
              example:
                message: Internal Server Error
    tags:
      - Products

  /products/{id}:
    get:
      summary: Get Product by ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the product
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              example:
                id: 1
                name: Product 1
                description: Description for Product 1
        "404":
          description: Product Not Found
          content:
            application/json:
              example:
                message: There is no such product.
        "500":
          description: Internal Server Error
          content:
            application/json:
              example:
                message: Internal Server Error
    tags:
      - Products
